"""Node entry point — runs inside each Docker container.

This is the top-level script executed by every federated learning node.
It orchestrates the full lifecycle of a single participant in the
decentralised training experiment:

    - Read per-node YAML config (mounted by Docker at /config/node.yaml).
    - Seed all random number generators for reproducible model init.
    - Load the pre-partitioned dataset (.npz file from /data/).
    - Build the model (tf.Module subclass).
    - Create the federation algorithm (e.g. D-PSGD).
    - Start the TCP transport server for incoming messages.
    - Create the ConnectionPool for outgoing messages.
    - Apply tc/netem traffic shaping rules.
    - Register the engine's message handler before connections are established.
    - Connect to the monitor and all neighbors.
    - Run the training loop.
    - Shut down cleanly.

The node itself is stateless between runs — all config comes from the
mounted YAML file and all data comes from the mounted .npz partition.
"""

from __future__ import annotations

import asyncio
import logging
import os
import random
import signal
import sys
from pathlib import Path

import numpy as np
import tensorflow as tf
import yaml

from src.algorithms.adpsgd import ADPSGD
from src.algorithms.base import FederationAlgorithm
from src.algorithms.dpsgd import DPSGD
from src.algorithms.fedavg import FedAvg
from src.algorithms.gossip_sgd import GossipSGD
from src.datasets.cifar10 import CIFAR10Dataset
from src.datasets.femnist import FEMNISTDataset
from src.datasets.mnist import MNISTDataset
from src.models.base import FederationModel
from src.models.cnn import CNNModelDef
from src.models.deep_cnn import DeepCNNModelDef
from src.models.femnist_cnn import FEMNISTCNNModelDef
from src.models.femnist_cnn_distributed import FEMNISTCNNDistributedModelDef
from src.models.mlp import MLPModelDef
from src.network.connection_pool import ConnectionPool
from src.network.transport import TransportServer
from src.tc.setup import apply_tc_rules
from src.training.engine import TrainingEngine

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Registries — maps config strings to implementation classes.
# New datasets, models, or algorithms are added here.
# NOTE: DATASET_REGISTRY must stay in sync with src/launcher.py.
# ---------------------------------------------------------------------------

DATASET_REGISTRY: dict[str, type] = {
    "mnist": MNISTDataset,
    "cifar10": CIFAR10Dataset,
    "femnist": FEMNISTDataset,
}

MODEL_REGISTRY: dict[str, type[FederationModel]] = {
    "mlp": MLPModelDef,
    "cnn": CNNModelDef,
    "deep_cnn": DeepCNNModelDef,
    "femnist_cnn": FEMNISTCNNModelDef,
    "femnist_cnn_distributed": FEMNISTCNNDistributedModelDef,
}

ALGORITHM_REGISTRY: dict[str, type[FederationAlgorithm]] = {
    "dpsgd": DPSGD,
    "adpsgd": ADPSGD,
    "gossip_sgd": GossipSGD,
    "fedavg": FedAvg,
}


def seed_everything(seed: int) -> None:
    """Seed all RNGs so that every node initialises identical model weights.

    In decentralised FL all nodes must start from the same initial parameters
    (no pre-training broadcast).  We achieve this by giving every container
    the same ``seed`` value in the config and seeding all relevant RNGs here.

    ``keras.utils.set_random_seed`` handles the Keras 3 backend RNG, which
    controls Dense/Conv layer initializers independently from ``tf.random``.
    We also seed Python, NumPy, and TF explicitly for completeness.
    """
    import keras

    keras.utils.set_random_seed(seed)
    random.seed(seed)
    np.random.seed(seed)
    tf.random.set_seed(seed)
    os.environ["TF_DETERMINISTIC_OPS"] = "1"


async def run_node(config: dict) -> None:
    """Main node coroutine — drives the full lifecycle described above.

    The config dict is loaded from the per-node YAML file generated by the
    config generator.  It contains identity info (node_id, ip, port),
    the neighbor list, training hyper-parameters, DSCP mapping, and
    monitor coordinates.
    """
    node_id = config["node_id"]
    node_ip = config["ip"]
    node_port = config["port"]
    role = config.get("role", "worker")
    seed = config.get("seed", 42)
    training_config = config["training"]
    neighbors = config["neighbors"]
    monitor_ip = config.get("monitor_ip")
    monitor_port = config.get("monitor_port", 5100)

    # DSCP mapping and traffic class count come from the top-level config.
    # In monolithic mode (or when not specified) there's a single class with
    # DSCP 0 (best effort).  In per-layer mode the generator provides the
    # full mapping so each traffic class gets its own DSCP codepoint.
    dscp_mapping = config.get("dscp_mapping", {0: 0})
    # Ensure keys are ints (YAML may parse them as strings in some edge cases)
    dscp_mapping = {int(k): int(v) for k, v in dscp_mapping.items()}
    num_traffic_classes = config.get("num_traffic_classes", 1)

    logger.info(
        f"[{node_id}] Starting node (role={role}, ip={node_ip}, "
        f"traffic_classes={num_traffic_classes})"
    )

    # ---- 1. Seed randomness ----
    seed_everything(seed)

    # ---- 2. Load dataset ----
    # The generator produces "dataset": "mnist" (string) — handle both
    # a plain string and a dict with a "name" key for forward compat.
    ds_conf = training_config["dataset"]
    dataset_name = ds_conf if isinstance(ds_conf, str) else ds_conf["name"]
    dataset_cls = DATASET_REGISTRY.get(dataset_name)
    if dataset_cls is None:
        raise ValueError(f"Unknown dataset: {dataset_name}")
    dataset = dataset_cls()

    # The launcher pre-partitions the dataset on the host and saves one .npz
    # per node, named after the Docker service (node-0.npz, node-1.npz, ...).
    # The entire data directory is bind-mounted at DATA_DIR inside the
    # container, so the node just loads its own file by name.
    data_dir = os.environ.get("DATA_DIR", "/data")
    data_file = Path(data_dir) / f"{node_id}.npz"
    logger.info(f"[{node_id}] Loading dataset from {data_file}")
    dataset.load_from_file(str(data_file))

    x_train, y_train = dataset.get_train_data()
    x_val, y_val = dataset.get_val_data()
    logger.info(
        f"[{node_id}] Dataset loaded: {len(x_train)} train, {len(x_val)} val samples"
    )

    # K0 (writeup/12 §3): evaluate on the shared global held-out test set
    # (identical across every node, already shipped in each partition's .npz
    # as x_test/y_test) instead of the per-node local val split, which is
    # tiny and class-skewed under Dirichlet partitioning and drives the ~4pp
    # cross-seed accuracy noise that swamps the non-inferiority margin.
    # Reported through the existing val_accuracy field.
    if bool(training_config.get("global_eval", False)):
        x_eval, y_eval = dataset.get_test_data()
        logger.info(
            f"[{node_id}] global_eval=ON: val metrics on shared held-out "
            f"test set ({len(x_eval)} samples)"
        )
    else:
        x_eval, y_eval = x_val, y_val

    # ---- 3. Build model ----
    model_name = training_config["model"]
    model_def = MODEL_REGISTRY.get(model_name)
    if model_def is None:
        raise ValueError(f"Unknown model: {model_name}")
    model = model_def().build(
        input_shape=dataset.get_input_shape(),
        num_classes=dataset.get_num_classes(),
    )
    param_count = FederationModel.get_parameter_count(model)
    logger.info(f"[{node_id}] Model '{model_name}' built: {param_count} parameters")

    # ---- 4. Create algorithm ----
    algo_name = training_config["algorithm"]
    algo_cls = ALGORITHM_REGISTRY.get(algo_name)
    if algo_cls is None:
        raise ValueError(f"Unknown algorithm: {algo_name}")
    neighbor_ids = [n.get("neighbor_id", n.get("id")) for n in neighbors]
    algorithm = algo_cls(
        node_id=node_id,
        neighbors=neighbor_ids,
        config=training_config,
    )

    # ---- 5. Start transport server ----
    # The server listens for incoming TCP connections from neighbors.
    # It must be up before we connect outward, because peers may start
    # sending as soon as *their* outbound connection succeeds.
    server = TransportServer(host="0.0.0.0", port=node_port)
    await server.start()

    # ---- 6. Create connection pool ----
    # The pool manages outgoing TCP sockets.  In monolithic mode it opens
    # one socket per neighbor (all on DSCP 0).  In per-layer mode it opens
    # num_traffic_classes sockets per neighbor, each with a different TOS
    # byte derived from the DSCP mapping, so the kernel marks packets for
    # the correct traffic class.
    pool = ConnectionPool(source_node=node_id, dscp_mapping=dscp_mapping)

    # ---- 7. Apply tc/netem traffic shaping rules ----
    # If this node has outgoing edges with QoS parameters, set up HTB +
    # netem rules on the container's egress interface.  This must happen
    # before any data flows so that the tc filters are in place when the
    # first packets are sent.  If tc setup fails (e.g. running outside
    # Docker without NET_ADMIN capability), training continues without
    # traffic shaping — the warning is enough for the user to diagnose.
    outgoing_edges = config.get("outgoing_edges", [])
    if outgoing_edges:
        try:
            apply_tc_rules("eth0", outgoing_edges, dscp_mapping)
            logger.info(f"[{node_id}] TC rules applied on eth0")
        except Exception as e:
            logger.warning(
                f"[{node_id}] TC setup failed (continuing without "
                f"traffic shaping): {e}"
            )

    # ---- 8. Create training engine and register handler BEFORE connecting ----
    # The message handler must be registered before any connections are
    # established.  If a faster neighbor connects and immediately sends an
    # update, the server would silently drop it if no handler was set yet.
    # By registering now we guarantee every message is captured.
    engine = TrainingEngine(
        node_id=node_id,
        model=model,
        algorithm=algorithm,
        server=server,
        pool=pool,
        config=training_config,
    )
    engine.monitor_ip = monitor_ip
    engine.monitor_port = monitor_port
    # Edge bandwidth info: outgoing edges feed the assignment strategies'
    # `bandwidths` input, incoming edges feed the receiver-side watchdog
    # fluid bound (gate rulings G1/G4).  Without these the engine degrades
    # gracefully (bandwidths=inf, watchdog disarmed) but measures nothing.
    engine.outgoing_edges = config.get("outgoing_edges", [])
    engine.incoming_edges = config.get("incoming_edges", [])
    engine._register_message_handler()

    # ---- 9. Connect to monitor and neighbors ----
    # Monitor is always on a single socket (class 0) since metrics don't
    # need QoS differentiation.
    if monitor_ip:
        try:
            await pool.connect(
                "monitor", monitor_ip, monitor_port,
                num_classes=1,
                max_retries=15, retry_delay=2.0,
            )
            logger.info(f"[{node_id}] Connected to monitor")
        except ConnectionError as e:
            logger.warning(f"[{node_id}] Could not connect to monitor: {e}")

    # Neighbor connections use the full traffic class count.  In monolithic
    # mode num_traffic_classes is 1, so each neighbor gets one socket.  In
    # per-layer mode each neighbor gets num_traffic_classes sockets.  Each
    # class socket's SO_SNDBUF is pinned to ~250 ms of the edge's shaped
    # class bandwidth (gate ruling G1, pre-run fix 2) so send back-pressure
    # tracks wire drain instead of kernel-buffer acceptance; unshaped
    # classes keep autotuning.
    for neighbor in neighbors:
        nid = neighbor.get("neighbor_id", neighbor.get("id"))
        nip = neighbor["ip"]
        nport = neighbor["port"]
        edge = next(
            (e for e in outgoing_edges if f"node-{e['dst']}" == nid), None
        )
        class_bw: dict[int, float] | None = None
        if edge is not None:
            class_bw = {
                int(cls): (
                    float(params["bandwidth_mbps"])
                    if params.get("bandwidth_mbps") is not None
                    else float("inf")
                )
                for cls, params in (edge.get("classes") or {}).items()
            }
        await pool.connect(
            nid, nip, nport,
            num_classes=num_traffic_classes,
            max_retries=30, retry_delay=2.0,
            class_bandwidths_mbps=class_bw,
        )

    logger.info(f"[{node_id}] Connected to {len(neighbors)} neighbors")

    # ---- 10. Run training ----
    # Centralized algorithms (FedAvg) use a dedicated aggregator loop for
    # the node designated as aggregator.  Workers in centralized algorithms
    # use the standard sync loop — the algorithm's methods handle the
    # centralized communication pattern (send to aggregator, receive
    # global model) transparently.
    try:
        if algorithm.is_centralized and role == "aggregator":
            metrics = await engine.run_aggregator(
                x_train, y_train, x_eval, y_eval,
            )
        elif algorithm.is_synchronous:
            metrics = await engine.run_sync(x_train, y_train, x_eval, y_eval)
        else:
            metrics = await engine.run_async(x_train, y_train, x_eval, y_eval)
    except Exception as e:
        logger.error(f"[{node_id}] Training failed: {e}", exc_info=True)
        raise
    finally:
        # ---- 11. Cleanup ----
        # Grace period: the last broadcast (aggregator → workers) and the
        # last MetricsReport (workers/aggregator → monitor) may still be
        # in flight when this node finishes its training loop.  pool.close_all()
        # uses sock.close() which is an abrupt close and risks RST'ing
        # in-flight bytes, causing the receiver to lose them.  Sleeping
        # briefly lets those final messages drain out cleanly.  Cheap
        # belt-and-braces fix; a proper FIN-based shutdown in
        # ConnectionPool is the long-term solution.
        await asyncio.sleep(2.0)
        await pool.close_all()
        await server.stop()
        logger.info(f"[{node_id}] Shutdown complete")


def main() -> None:
    """Entry point: load config and run.

    The node config YAML path is taken from the NODE_CONFIG environment
    variable (set in docker-compose) or from the first CLI argument.
    """
    config_path = os.environ.get("NODE_CONFIG", "/config/node.yaml")

    # Also support passing config as CLI arg (useful for local testing)
    if len(sys.argv) > 1:
        config_path = sys.argv[1]

    logger.info(f"Loading node config from {config_path}")
    with open(config_path) as f:
        config = yaml.safe_load(f)

    # Handle graceful shutdown — cancel all asyncio tasks on SIGTERM/SIGINT
    # so the finally blocks in run_node() can run cleanup.
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)

    def handle_signal(sig: int) -> None:
        logger.info(f"Received signal {sig}, shutting down...")
        for task in asyncio.all_tasks(loop):
            task.cancel()

    for sig in (signal.SIGTERM, signal.SIGINT):
        loop.add_signal_handler(sig, handle_signal, sig)

    try:
        loop.run_until_complete(run_node(config))
    except (asyncio.CancelledError, KeyboardInterrupt):
        logger.info("Node cancelled")
    finally:
        loop.close()


if __name__ == "__main__":
    main()
